In [15]:
import numpy as np
import pandas as pd

In [16]:
# Read file from local using pandas

a=pd.read_csv('/home/abhinav/Downloads/heart.csv')
a.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   52    1   0       125   212    0        1      168      0      1.0      2   
1   53    1   0       140   203    1        0      155      1      3.1      0   
2   70    1   0       145   174    0        1      125      1      2.6      0   
3   61    1   0       148   203    0        1      161      0      0.0      2   
4   62    0   0       138   294    1        1      106      0      1.9      1   

   ca  thal  target  
0   2     3       0  
1   0     3       0  
2   0     3       0  
3   1     3       0  
4   3     2       0

In [17]:
#Set input label

x=a.iloc[:,:-1].values
print(x)

[[52.  1.  0. ...  2.  2.  3.]
 [53.  1.  0. ...  0.  0.  3.]
 [70.  1.  0. ...  0.  0.  3.]
 ...
 [47.  1.  0. ...  1.  1.  2.]
 [50.  0.  0. ...  2.  0.  2.]
 [54.  1.  0. ...  1.  1.  3.]]


In [18]:
# Set output label

y=a.iloc[:,-1].values
print(y)

[0 0 0 ... 0 1 0]


In [19]:
# Set training and testing data

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.30,random_state=1)
print(x_train)

[[62.  0.  0. ...  1.  3.  2.]
 [68.  1.  2. ...  1.  0.  3.]
 [66.  0.  2. ...  1.  1.  2.]
 ...
 [56.  1.  0. ...  1.  1.  2.]
 [62.  1.  0. ...  1.  2.  3.]
 [64.  1.  3. ...  1.  0.  3.]]


In [20]:
# performing normalization 

from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
scaler.fit(x_train)
x_train=scaler.fit_transform(x_train)
x_test=scaler.fit_transform(x_test)
print(x_train)

[[ 0.84287068 -1.49322796 -0.92148277 ... -0.61823273  2.20430609
  -0.52060454]
 [ 1.51262126  0.66969011  1.08368611 ... -0.61823273 -0.72071698
   1.10232353]
 [ 1.28937106 -1.49322796  1.08368611 ... -0.61823273  0.25429071
  -0.52060454]
 ...
 [ 0.17312009  0.66969011 -0.92148277 ... -0.61823273  0.25429071
  -0.52060454]
 [ 0.84287068  0.66969011 -0.92148277 ... -0.61823273  1.2292984
   1.10232353]
 [ 1.06612087  0.66969011  2.08627055 ... -0.61823273 -0.72071698
   1.10232353]]


In [21]:
# performing KNN algorithm

from sklearn.neighbors import KNeighborsClassifier
classifier=KNeighborsClassifier(n_neighbors=3)
classifier.fit(x_train,y_train)

KNeighborsClassifier(n_neighbors=3)

In [22]:
# set prediction 

y_predict=classifier.predict(x_test)

In [23]:
# make prediction
print(classifier.predict([[50,1,0,130,200,1,0,150,0,1.2,2,0,3]]))

[1]


In [24]:
#print the confution matrix and accuracy score

from sklearn.metrics import confusion_matrix,accuracy_score
result=confusion_matrix(y_test,y_predict)
print(result)
result1=accuracy_score(y_test,y_predict)
print(result1)

[[145  16]
 [  8 139]]
0.922077922077922


In [25]:
# print the classification report

from sklearn.metrics import classification_report
print(classification_report(y_test,y_predict))

              precision    recall  f1-score   support

           0       0.95      0.90      0.92       161
           1       0.90      0.95      0.92       147

    accuracy                           0.92       308
   macro avg       0.92      0.92      0.92       308
weighted avg       0.92      0.92      0.92       308

